Repository fog/fog-vsphere, pull requests merged in 2018-11, with the labels that each got.

#164 Relocate
  lib/fog/vsphere/requests/compute/vm_relocate.rb
Labels: Ready for merge

#172 Expose extraConfig from user_data for vm_clone
  lib/fog/vsphere/requests/compute/cloudinit_to_customspec.rb
Labels: Enhancement, Ready for merge

#171 Support getting folder types other than vm folder
  lib/fog/vsphere/requests/compute/get_folder.rb
Labels: Enhancement, Ready for merge

#176 fetch datacenter by vm_mob_ref.path if user does not have permission to access hosts
  lib/fog/vsphere/compute.rb
Labels: Enhancement, Ready for merge

#178 Disable module length on compute.rb to make tests happy
  lib/fog/vsphere/compute.rb
Labels: Ready for merge

#180 Fixes #179 - Update vm_clone template to not always be false.
  lib/fog/vsphere/requests/compute/vm_clone.rb
Labels: Enhancement, Needs Testing on Foreman, Needs testing, Not yet reviewed
