Repository fog/fog-vsphere, pull requests merged in 2018-10, with the labels that each got.

#156 Remove gemnasium and update markdown to markdown-lint
  CONTRIBUTING.md
  README.md
Labels: Enhancement, Not yet reviewed

#157 Help prevent hard fail on nil undefined legacy networks.
  lib/fog/vsphere/requests/compute/list_vm_interfaces.rb
Labels: Bug, Not yet reviewed

#159 speed up datastore loading
  lib/fog/vsphere/requests/compute/get_cluster.rb
  lib/fog/vsphere/requests/compute/list_datastores.rb
Labels: Ready for merge

#160 speed up storage pod loading
  lib/fog/vsphere/requests/compute/create_vm.rb
  lib/fog/vsphere/requests/compute/get_datastore.rb
  lib/fog/vsphere/requests/compute/get_storage_pod.rb
  lib/fog/vsphere/requests/compute/list_datastores.rb
  lib/fog/vsphere/requests/compute/list_storage_pods.rb
Labels: Enhancement, Ready for merge

#158 speed up folder loading
  lib/fog/vsphere/requests/compute/get_folder.rb
  lib/fog/vsphere/requests/compute/list_folders.rb
Labels: Enhancement, Ready for merge
