Repository fog/fog-vsphere, pull requests merged in 2019-07, with the labels that each got.

#214 Grab DC if within a folder
  lib/fog/vsphere/models/compute/datacenter.rb
Labels: Bug

#219 Fixes #218 - Annotation Notes are not set in Image based builds
  lib/fog/vsphere/requests/compute/vm_clone.rb
Labels: Bug, Needs Testing on Foreman

#217 Fixes #216 - cloning disks thin relocation and storagePod location
  lib/fog/vsphere/requests/compute/create_vm.rb
  lib/fog/vsphere/requests/compute/vm_clone.rb
Labels: Bug, Ready for merge

#221 Release version 3.2.0
  CHANGELOG.md
  CONTRIBUTORS.md
  lib/fog/vsphere/version.rb
Labels: Ready for merge
