Repository fog/fog-vsphere, pull requests merged in 2020-07, with the labels that each got.

#255 Add ability to create update and delete Resource Pools #253
  lib/fog/vsphere/compute.rb
  lib/fog/vsphere/requests/compute/create_resource_pool.rb
  lib/fog/vsphere/requests/compute/destroy_resource_pool.rb
  lib/fog/vsphere/requests/compute/update_resource_pool.rb
Labels: Enhancement

#254 Check datastore for existence prior vm_clone
  lib/fog/vsphere/requests/compute/vm_clone.rb
Labels: Enhancement, Ready for merge

#260 Remove code climate
  .travis.yml
Labels: Ready for merge
